version: '3.1'

services:
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      mem_limit: 512m
      cpus: 0.25
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - 9090:9090
      restart: unless-stopped
      volumes:
        - ./infraestructure/prometheus:/etc/prometheus
        - prom_data:/prometheus
      network_mode: "host"

  grafana:
      image: grafana/grafana
      container_name: grafana
      mem_limit: 512m
      cpus: 0.25
      ports:
        - 3000:3000
      restart: unless-stopped
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=grafana
      volumes:
        - ./infraestructure/grafana:/etc/grafana/provisioning/datasources
      network_mode: "host"  

  transcriptor:
    build: .
    image: speechtotext:v2
    restart: always
    env_file: .env
    network_mode: "host"
    volumes:
      - ./download/models:/app/models
    command: ["uvicorn","main:app"]

volumes:
  prom_data: