version: '3.1'

services:

  transcriptor:
    build: .
    image: speechtotext:v2
    restart: always
    env_file: .env
    network_mode: "host"
    volumes:
      - ./models:/app/models
    command: ["uvicorn","main:app"]