version: '3.1'

services:

  transcriptor:
    build: .
    image: speechtotext:v1
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    network_mode: "host"
    volumes:
      - ./models:/app/models
    command: ["uvicorn","main:app"]